url-hint.el
url-get-url-at-point returns nil when cursor is on end-of-buffer.
`google.com` isn't opened by `M-x url-hint-open-all-urls`. Because `url-get-url-at-point` returns nil when cursor is end-of-buffer(EOB). So this change specifies beginning of URL explicitly for avoiding this issue.
```
http://www.yahoo.com
http://www.google.com[EOB]
```
This issue is not occurred when using avy jump command.
=> Specify point explicitly

link-hint.el
If [avy-single-candidate-jump](https://github.com/abo-abo/avy/blob/master/avy.el#L247) is `nil` (default is `t`), then avy commands should still prompt even if there is only one match.
=> Respect avy-single-candidate-jump

link-hint.el
Emacs shows windows paths as "d:/some/dir". Now regexp matches them too.
=> Add windows support

link-hint.el
Without the UPDATE argument, `window-end' return value is wrong (and
can cause part of the links being missed) e.g. when calling hint-link
from a transient multiline completion window (which closes before the
hints are generated).
---
I don't know if some of the other window-end calls might need fixing,
too; my cursory experience seems to indicate that at least some of
them do not.
=> link-hint--collect-visible-links: Fix redisplay-related bug

link-hint.el
```
link-hint.el:957:24:Warning: ‘avy--process’ is an obsolete function (as of
0.4.0); use ‘avy-process’ instead.
```
=> Fix obsoleted warning

link-hint.el
closes #26 
Fixes a bug that didn't allow minor-mode links to work and adds support for `org-link-minor-mode`.
=> Support org link minor mode

link-hint.el
Like the other interactive commands in link-hint, this one should be autoloaded.
This PR also fixes the `SPC x y` key binding in Spacemacs.
=> Autoload link-hint-copy-link-at-point

link-hint.el
This adds support for a couple of major modes derived from `markdown-mode`, i.e. `gfm-mode` (for GitHub-flavoured Markdown) and `markdown-view-mode` (readonly).
=> Support Markdown-derived modes

README.org, link-hint.el
Let me know if this can be improved at all. I tried the generic button type and it didn't seem to work. I think because the widgets used in notmuch use overlays rather than text-properties (although I'm not too sure about the difference)
=> Add support for notmuch-hello links

README.org, link-hint.el
Now you can jump to any visible match in [deadgrep](https://github.com/Wilfred/deadgrep) using link-hint.
=> Add a link type for deadgrep matches

link-hint.el
Fixes #182. It skips the entire loop if `epkg` is unavailable.
=> Check if epkg is available to prevent errors

link-hint.el
If you turn on `compilation-minor-mode` in modes such as `magit-process-buffer` and `vterm-mode`, you can jump to error locations quickly. It would be handy if link-hint supported this feature, and it becomes possible with this change.
=> Add compilation-minor-mode

link-hint.el
2021-07-01  Valeriy Litkovskyy  <vlr.ltkvsk@protonmail.com>
* link-hint.el (link-hint-action-messages, link-hint-types): better custom types
=> better custom types for action-messages and types

README.org, link-hint.el
For functions where bounds are always passed, remove default window-start and
window-end bounds and make bounds required arguments. Where window-end is
actually needed, always call it with UPDATE non-nil. This makes things clearer
so that issues like #181 won't happen again. Fixes #36.
Make bound argument mandatory on all :next functions (it is always passed).
Functions using window-end previously:
- link-hint--find-regexp - make bounds mandatory and remove window-end
- used by link-hint--find-file-link - always passes non-nil bounds
- used by link-hint--next-regexp - optional end bound, make mandatory
- used by link-hint--next-text-url - :next function, so will always get end
bound
- link-hint--next-widget - make bound mandatory (used only as :next function;
will always get end bound)
- …
=> Remove unnecessary window-end calls

link-hint.el
Currently links aren't selectable when using w3m as a renderer in notmuch-show-mode.
=> Added support for notmuch with w3m as renderer

link-hint.el
I think this solves #221 
I have tested it in org-agenda and org-mode buffers and it seems to work without triggering the warning.
=> fix: warning org-element-at-point cannot be used in non-Org buffer

link-hint.el
`compile` can run a command in a comint buffer with `compilation-shell-minor-mode` enabled. Link-hint already supports non-comint compilation buffers, and this PR will add the same functionality to comint compilation.
=> Add compilation-shell-minor-mode

link-hint.el
Hi,
The deadgrep support seems to be broken. It no longer highlights matches, and this PR fixes the issue.
Also `link-hint--deadgrep-link-at-point-p` returned only a line number, which is somewhat hard to understand. I would propose a change to the `filename:line-number` format.
Finally, it would be nice if the links were opened in another window so I can browse many links using `link-hint`. What do you think? Is it better to leave it as it is?
=> Fix the regression of deadgrep support and a few other suggestions

link-hint.el
I think the key should be `:parse`, not `:parser`.
Currently, `link-hint-copy-link` fails to copy links on Markdown files
=> fix: wrong key when define parser for markdown links

link-hint.el
See https://codeberg.org/martianh/mastodon.el/pulls/644 which define a button types for buttons for mastodon buffers however link-hint ends up opening the shr-url instead of more appropriate button.
=> Don't use link-hint-shr-url for mastodon buffers
